/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface PreviousYearPaper {
    id: bigint;
    url: string;
    subject: string;
    year: bigint;
    examName: string;
}
export interface DailyPollutionEntry {
    id: bigint;
    day: bigint;
    recommendations: string;
    pollutionSource: string;
    airQuality: string;
}
export interface StudyMaterial {
    id: bigint;
    url: string;
    title: string;
    subject: string;
    contentType: ContentType;
}
export interface DailyTestSeriesEntry {
    id: bigint;
    day: bigint;
    subject: string;
    testName: string;
    description: string;
    questionsUrl: string;
    videoLectureUrl: string;
    answersUrl: string;
}
export interface UserProfile {
    name: string;
}
export enum ContentType {
    Course = "Course",
    VideoLecture = "VideoLecture",
    Book = "Book",
    Music = "Music",
    Audio = "Audio",
    PdfBook = "PdfBook"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDailyPollutionEntry(day: bigint, airQuality: string, pollutionSource: string, recommendations: string): Promise<bigint>;
    addPreviousYearPaper(year: bigint, subject: string, examName: string, url: string): Promise<bigint>;
    addStudyMaterial(title: string, subject: string, contentType: ContentType, url: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDailyPollutionEntry(id: bigint): Promise<void>;
    deletePreviousYearPaper(id: bigint): Promise<void>;
    deleteStudyMaterial(id: bigint): Promise<void>;
    getAllDailyPollutionEntries(): Promise<Array<DailyPollutionEntry>>;
    getAllDailyTestSeries(): Promise<Array<DailyTestSeriesEntry>>;
    getAllPreviousYearPapers(): Promise<Array<PreviousYearPaper>>;
    getAllStudyMaterials(): Promise<Array<StudyMaterial>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDailyPollutionByDay(day: bigint): Promise<Array<DailyPollutionEntry>>;
    getDailyTestSeriesByDay(day: bigint): Promise<Array<DailyTestSeriesEntry>>;
    getDailyTestSeriesBySubject(subject: string): Promise<Array<DailyTestSeriesEntry>>;
    getPreviousYearPaperById(id: bigint): Promise<PreviousYearPaper | null>;
    getPreviousYearPapersByExam(examName: string): Promise<Array<PreviousYearPaper>>;
    getPreviousYearPapersBySubject(subject: string): Promise<Array<PreviousYearPaper>>;
    getStudyMaterialById(id: bigint): Promise<StudyMaterial | null>;
    getStudyMaterialsBySubject(subject: string): Promise<Array<StudyMaterial>>;
    getStudyMaterialsByType(contentType: ContentType): Promise<Array<StudyMaterial>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { ContentType as _ContentType, PreviousYearPaper as _PreviousYearPaper, StudyMaterial as _StudyMaterial, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDailyPollutionEntry(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyPollutionEntry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyPollutionEntry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addPreviousYearPaper(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPreviousYearPaper(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPreviousYearPaper(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addStudyMaterial(arg0: string, arg1: string, arg2: ContentType, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addStudyMaterial(arg0, arg1, to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addStudyMaterial(arg0, arg1, to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDailyPollutionEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyPollutionEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyPollutionEntry(arg0);
            return result;
        }
    }
    async deletePreviousYearPaper(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePreviousYearPaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePreviousYearPaper(arg0);
            return result;
        }
    }
    async deleteStudyMaterial(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStudyMaterial(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStudyMaterial(arg0);
            return result;
        }
    }
    async getAllDailyPollutionEntries(): Promise<Array<DailyPollutionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyPollutionEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyPollutionEntries();
            return result;
        }
    }
    async getAllDailyTestSeries(): Promise<Array<DailyTestSeriesEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDailyTestSeries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDailyTestSeries();
            return result;
        }
    }
    async getAllPreviousYearPapers(): Promise<Array<PreviousYearPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPreviousYearPapers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPreviousYearPapers();
            return result;
        }
    }
    async getAllStudyMaterials(): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudyMaterials();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudyMaterials();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyPollutionByDay(arg0: bigint): Promise<Array<DailyPollutionEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPollutionByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPollutionByDay(arg0);
            return result;
        }
    }
    async getDailyTestSeriesByDay(arg0: bigint): Promise<Array<DailyTestSeriesEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTestSeriesByDay(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTestSeriesByDay(arg0);
            return result;
        }
    }
    async getDailyTestSeriesBySubject(arg0: string): Promise<Array<DailyTestSeriesEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyTestSeriesBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyTestSeriesBySubject(arg0);
            return result;
        }
    }
    async getPreviousYearPaperById(arg0: bigint): Promise<PreviousYearPaper | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreviousYearPaperById(arg0);
                return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreviousYearPaperById(arg0);
            return from_candid_opt_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPreviousYearPapersByExam(arg0: string): Promise<Array<PreviousYearPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreviousYearPapersByExam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreviousYearPapersByExam(arg0);
            return result;
        }
    }
    async getPreviousYearPapersBySubject(arg0: string): Promise<Array<PreviousYearPaper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPreviousYearPapersBySubject(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPreviousYearPapersBySubject(arg0);
            return result;
        }
    }
    async getStudyMaterialById(arg0: bigint): Promise<StudyMaterial | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterialById(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterialById(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterialsBySubject(arg0: string): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterialsBySubject(arg0);
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterialsBySubject(arg0);
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudyMaterialsByType(arg0: ContentType): Promise<Array<StudyMaterial>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudyMaterialsByType(to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudyMaterialsByType(to_candid_ContentType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
}
function from_candid_ContentType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ContentType): ContentType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_StudyMaterial_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudyMaterial): StudyMaterial {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PreviousYearPaper]): PreviousYearPaper | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_StudyMaterial]): StudyMaterial | null {
    return value.length === 0 ? null : from_candid_StudyMaterial_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    url: string;
    title: string;
    subject: string;
    contentType: _ContentType;
}): {
    id: bigint;
    url: string;
    title: string;
    subject: string;
    contentType: ContentType;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        subject: value.subject,
        contentType: from_candid_ContentType_n8(_uploadFile, _downloadFile, value.contentType)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Course: null;
} | {
    VideoLecture: null;
} | {
    Book: null;
} | {
    Music: null;
} | {
    Audio: null;
} | {
    PdfBook: null;
}): ContentType {
    return "Course" in value ? ContentType.Course : "VideoLecture" in value ? ContentType.VideoLecture : "Book" in value ? ContentType.Book : "Music" in value ? ContentType.Music : "Audio" in value ? ContentType.Audio : "PdfBook" in value ? ContentType.PdfBook : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudyMaterial>): Array<StudyMaterial> {
    return value.map((x)=>from_candid_StudyMaterial_n6(_uploadFile, _downloadFile, x));
}
function to_candid_ContentType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): _ContentType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ContentType): {
    Course: null;
} | {
    VideoLecture: null;
} | {
    Book: null;
} | {
    Music: null;
} | {
    Audio: null;
} | {
    PdfBook: null;
} {
    return value == ContentType.Course ? {
        Course: null
    } : value == ContentType.VideoLecture ? {
        VideoLecture: null
    } : value == ContentType.Book ? {
        Book: null
    } : value == ContentType.Music ? {
        Music: null
    } : value == ContentType.Audio ? {
        Audio: null
    } : value == ContentType.PdfBook ? {
        PdfBook: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
